### ISSUE TITLE
Query validation shows same error twice

### ISSUE THREAD

**Issue by furkansenharputlu** [TykTechnologies/graphql-go-tools#57]
<img width="632" alt="Ekran Resmi 2020-06-16 13 28 22" src="https://user-images.githubusercontent.com/25665432/84763983-b4891900-afd5-11ea-82f1-309be4745844.png">

This is returned from:
```normalizationResult, err := gqlRequest.Normalize(m.Spec.GraphQLExecutor.Schema)```

**Comment by ilijabojanovic** [comment]
Verified
